site_name: Fishing Doc
site_url: https://frc-3566-docs.readthedocs.io/
nav:
    - Home: README.md
    - About: about.md
    - RoboRIO: roborio/
    - Coprocessor: coprocessor/
    - Driver Station: driver_station/
    - Hardware & Wiring: hardware&wiring/README.md
    - Scouting: scouting/
theme:
  name: swan