site_name: FRC 3566 Docs
site_url: https://frc-3566-docs.readthedocs.org/
nav:
    - Home: index.md
    - About: about.md
    - RoboRIO: roborio/
    - Coprocessor: coprocessor/
    - Driver Station: driver_station/
    - Other Hardwares: other_hardwares/ 
    - Scouting: scouting/
theme: readthedocs