site_name: Fishing Doc
site_url: https://frc-3566-docs.readthedocs.io/
nav:
    - Home: index.md
    - About: about.md
    - RoboRIO: roborio/
    - Coprocessor: coprocessor/
    - Driver Station: driver_station/
    - Hardware & Wiring: hardware&wiring/ 
    - Scouting: scouting/
theme: readthedocs
